"print('Hello from My First Project')" 
"def greet(name):" 
"    print(f'Hello, {name}!')" 
"print('Welcome to my-first-project!')" 
"" 
"def calculate_sum(numbers):" 
"    return sum(numbers)" 
"" 
"def greet_return(name):" 
"    return f'Hello, {name}!'" 
"" 
"# Optimized sum using built-in function directly" 
"def calculate_sum_fast(numbers):" 
"    total = 0" 
"    for n in numbers:" 
"        total += n" 
"    return total" 
